### ISSUE TITLE
Pop-up too small

### ISSUE THREAD

**Issue by grahamperrin** [OpenDyslexic/firefox-extension#1]
Please, can you make the pop-up large enough to allow the switch etc. to be reached without scrolling?

![2018-05-25 19 29 57 waterfox](https://user-images.githubusercontent.com/192271/40560487-12d2ccb6-6052-11e8-8e34-1d8bed84e55f.png)

----

Incidentally, is this week's https://addons.mozilla.org/addon/opendyslexic-for-firefox/versions/?page=1#version-6.0.9 truly the first release for Firefox? (I vaguely recall trying this extension with Firefox, or Waterfox, months ago … maybe I used [Chrome Store Foxified](https://addons.mozilla.org/addon/chrome-store-foxified/) …)

**Comment by grahamperrin** [comment]
Incidentally (this shot, borrowed from a different issue): 

![2018-06-01 16 04 40 browsers](https://user-images.githubusercontent.com/192271/40848274-a07a0aca-65b6-11e8-9f1b-9c1bc295a996.png)

– during that test session, with Firefox 60.0.1_3,1 (not Waterfox), I somehow found it incredibly difficult to throw the switch to the left, to its _off_ position. 

After maybe twenty attempts the switch moved. I couldn't get a good sense of what caused the 'resistance' so it doesn't warrant a separate issue at this time, but maybe worth reviewing after this issue 1 is fixed. 

No rush. Thanks.

**Comment by RobertJGabriel** [comment]
Hey @grahamperrin This is sorted now :)
<img width="1212" alt="screen shot 2018-06-05 at 11 31 24 pm" src="https://user-images.githubusercontent.com/6218780/41017315-04618e62-691a-11e8-9159-ef2e0e3d4720.png">

**Comment by grahamperrin** [comment]
Fix confirmed, thanks 👍
